### ISSUE TITLE
Unmet dependencies from OBS repo

### ISSUE THREAD

**Issue by sphaero** [zeromq/libzmq#4471]
# Issue description

Can't install from OBS repo.

I'm using this in github actions:

```
   - name: add Debian Packages
      if: matrix.os == 'ubuntu-latest'
      uses: myci-actions/add-deb-repo@10
      with:
        repo-name: obs
        repo: deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_20.04/ ./
        keys-asc: https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_20.04/Release.key
        install: libzmq5 libzmq3-dev libglx-dev mesa-common-dev libasound2-dev libglew-dev libunwind-dev
```

This fails:

```
The following packages have unmet dependencies:
 libzmq5 : Depends: libpgm-5.2-0 (>= 5.1.116~dfsg) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

# Environment

* OS: github runner ubuntu latest (20.04)
